### PR TITLE
Add Continous Integration 

### LINKED ISSUE #10: Configue CI
consider adding:
- tox
- linter checking flake
- formatter checking autopep

### PR DESCRIPTION
**Pull request by SebChw**
closes #10

### CODE REVIEW

**Comment by kordc** [comment]
nice, maybe before flake8 we should add black/autopep8?
autopep8 is default in VSC https://code.visualstudio.com/docs/python/editing#_general-formatting-settings

**Comment by SebChw** [comment]
@kordc what do you mean? You want the code to be formatted automatically when pushed? If yes, I'd rather people formatted code by themselves to be aware of this.

**Comment by kordc** [comment]
@SebChw yep, I meant that. But fair enough, not a necessary thing to do. If so, the rest LGTM

**Review by kordc — APPROVED** [review]

**Comment by SebChw** [comment]
@kordc If we do this people won't know that they wrote badly formatted code, that's why I don't want to do so.

**Pull request merged**
